[package]
name = "rtoy_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.8.0"
gl = "0.14.0"
glfw = "0.59.0"
mlua = { version = "0.10.2", features = ["lua54", "macros"] }
serde = { version = "1.0.217", features = ["derive"] }
