[package]
name = "rtoy_module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10.2", features = ["lua54", "module"] }
rtoy_engine = { path = "../rtoy_engine" }